services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      REACT_APP_API_URL: http://localhost:3000
      PORT: 3001
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./public
          target: /app/public
        - action: rebuild
          path: ./package.json

volumes:
  pgdata:
