services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    environment:
      EXPO_PUBLIC_API_URL: http://localhost:3000
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: sync
          path: ./assets
          target: /app/assets
        - action: rebuild
          path: ./package.json
