export const API = {
    LOGIN: '/api/login',
    REGISTER: '/api/register',
    LOGOUT: '/api/logout',
    LEADERBOARD: '/api/leaderboard',
    SEARCH: '/api/search',
    ENTRIES: '/api/entries',
    ENTRY: (id: number) => `/api/entries/${id}`,
    ACTIVITY_TYPES: '/api/activity-types',
    ACTIVITY_TYPE: (id: number) => `/api/activity-types/${id}`,
    USER_ME: '/api/user/me',
    TOP_PERFORMERS: '/api/top-performers',
    USER_PROFILE: (id: number) => `/api/users/${id}`,
    USER_CHALLENGES: (id: number) => `/api/users/${id}/challenges`,
    USER_TEAMS: (id: number) => `/api/users/${id}/teams`,
    ENTRY_LIKES: (id: number) => `/api/entries/${id}/likes`,
    FORGOT_PASSWORD: '/api/auth/forgot-password',
    RESET_PASSWORD: '/api/auth/reset-password',
    CHALLENGES: '/api/challenges',
    CHALLENGE: (id: number) => `/api/challenges/${id}`,
    CHALLENGE_JOIN: (id: number) => `/api/challenges/${id}/join`,
    CHALLENGE_LEADERBOARD: (id: number) => `/api/challenges/${id}/leaderboard`,
    TEAMS: '/api/teams',
    TEAM: (id: number) => `/api/teams/${id}`,
    TEAM_JOIN: (id: number) => `/api/teams/${id}/join`,
    TEAM_LEADERBOARD: (id: number) => `/api/teams/${id}/leaderboard`,
    IMAGE_UPLOAD: '/api/images/upload',
    IMAGE_DELETE: (id: number) => `/api/images/${id}`,
};
